---
- name: Clone repo, build, push, and run Docker container on remote EC2 instance
  hosts: docker_host
  become: true
  vars:
    github_repo: "https://github.com/ravina-sawant/nodejs.git"
    clone_path: "/home/ubuntu/nodejs"
    image_name: ravina96/nodejs
    image_tag: latest  # Fixed typo
    container_name: nodejs
    dockerhub_username: "ravina1996"
    dockerhub_password: "ravina123"  # Hardcoded password (Not secure)

  tasks:

    - name: Install Git (if not installed)
      package:
        name: git
        state: present

    - name: Clone GitHub repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ clone_path }}"
        version: main
        force: yes  

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      register: login_result

    - name: Fail if Docker login unsuccessful
      fail:
        msg: "Docker login failed. Check credentials."
      when: login_result.failed is defined and login_result.failed

    - name: Build Docker image from cloned repository
      docker_image:
        source: build
        build:
          path: "{{ clone_path }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: no
      register: build_result

    - name: Push Docker image to Docker Hub
      command: docker push {{ image_name }}:{{ image_tag }}
      when: build_result.changed

    - name: Stop and remove existing container (if any)
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Run the container from the new image
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
